### ISSUE TITLE
Tests on poemWriter throw false positves

### ISSUE THREAD

**Issue by jminterwebs** [learn-co-curriculum/react-forms-lab#10]
@gj 

It is possible to pass all the test yet crash the server one using the poemWriter a second time.

On solutions that do not check to see with the poem is three lines long before validating the amount of word per line. So on any poem tested after the first initial poem the server will crash when code simillar to this is ran 

`function countWords(line) {
  return line.split(' ').filter(l => l).length;
}

function isValidPoem(poem) {
  const poemLines = poem.split('\n').filter(l => l);
  const isRightAmountOfLines = poemLines.length === 3;
  const hasRightAmountOfWords = countWords(poemLines[0]) === 5 && countWords(poemLines[1]) === 3 && countWords(poemLines[2]) === 5;
  return isRightAmountOfLines && hasRightAmountOfWords;
}`

It seems when poem is passed the second time it has now length therefore crashing the server.

**Comment by gj** [comment]
Hi @jminterwebs !

Would you mind including a stack trace of the error(s) you're seeing?

**Comment by realAndrewCohn** [comment]
The tests and solution branch have now been updated for this lab. closing issue
