### ISSUE TITLE
Unclear instructions?

### ISSUE THREAD

**Issue by meryldakin** [learn-co-curriculum/react-forms-lab#11]
> 7. The onSubmit callback prop should only be called if both fields are filled in (with any value).

This makes it sound like they need a ternary in the `onSubmit` property of the button to only call `this.handleSubmit` if the conditions are met. I don't THINK that's the intention but I could be wrong. If I'm correct, I would suggest wording it like this: 

> 7. The callback prop passed to the component should only be called if both fields are filled in (with any value).

**Comment by realAndrewCohn** [comment]
The readme has been updated to be clearer closing issue
