### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-forms-lab#14]
Several spelling and grammar issues in this lesson. 

"Make this a controlled component by adding the necessary props to these inputs. Their values should be saved in the component's state."  - needs to be pluralized properly 

"Remember that you can retrieve the inpiut name and value of an event.target from the JS event."  - def not how you spell input.

Probably a couple more too.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
