### ISSUE TITLE
Conflicting test

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-forms-lab#15]
In the README is says that a poem with leading/trailing whitespace is invalid, but the test says:

"should not show an error when the poem is valid but has extra whitespace"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the tests and content of this lab and removed the poem section to make the lab simpler and clearer.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
