### ISSUE TITLE
Controlled Compotents heading used twice

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/react-forms-lab#16]
"Controlled Components" is a section heading that appears twice in a row

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
