### ISSUE TITLE
Typo on 5th requirement for LoginForm

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/react-forms-lab#17]
"inpiut" should be "input"
"Remember that you can retrieve the inpiut name and value of an event.target from the JS event"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
