### ISSUE TITLE
Leading/Trailing whitespace. Whats the story?

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/react-forms-lab#18]
It seems like leading whitespace is a problem in the poem, but trailing is supposed to be ok.
But in the test, `const VALID_POEM_WITH_EXTRA_WHITESPACE = `${"word ".repeat(5)}
  ${"word ".repeat(3)}
${"word ".repeat(5)}  `;` 
the valid poem should not trip the error message.

Well, the valid poem over here has leading whitespace on the second line. backspacing that line and saving the test makes it fine. but in that case the only additional functionality the test requires is that multiple spaces as opposed to one are allowed as trailing.

I recommend changing line 17 of the poem test by backspacing to the start of the line. because the readme is quite explicitly ruling out leading whitespace.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have removed the poem portion of this lab to improve the focus of what the lab is trying to teach. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
