### ISSUE TITLE
THIS LAB!!!?

### ISSUE THREAD

**Issue by rogercodes1** [learn-co-curriculum/react-forms-lab#21]
please provide more details on what is expected of this lab. Where do we get the character amount? 
How do we know to set it to message? 
You guys can do better.

**Comment by maxwellbenton** [comment]
Thank you for  providing feedback.

We have updated the materials to help clarify, updated the tests and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
