### ISSUE TITLE
Tests fail if requirements are met for login form

### ISSUE THREAD

**Issue by tpetersen0308** [learn-co-curriculum/react-forms-lab#23]
Lines 62 and 99 of LoginForm-test.js test that it is _true_ that:

"The default form action is not being prevented when the form is submitted" (line 62)

"The `onSubmit` prop is not being called" (line 99)

But the lab requires that the default form action IS prevented and the onSubmit prop IS called, resulting in conflicts that make the tests unpassable. Changing these to false gets tests passing. Confirmed in the browser.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the tests for this lab and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
