### ISSUE TITLE
Can't run tests without running npm install --save raf

### ISSUE THREAD

**Issue by DGMarkel** [learn-co-curriculum/react-forms-lab#26]
I opened this lab and ran learn immediately. Without making any changes to my cloned repo, the tests threw a bunch of errors and wouldn't run. 

A quick google search led to the following solution:
npm install --save raf
Then as your first import in entry point, before React:
import 'raf/polyfill';

but it appears that just installing --save raf was enough to get the tests running.

**Comment by DGMarkel** [comment]
I opened this lab and ran learn immediately.  Without making any changes to my cloned repo, the tests threw a bunch of errors and wouldn't run.  There are too many lines of error to paste here, but here's a snippet from the top: This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://f
b.me/react-polyfills
module.js:471 

A quick google search led to the following solution: 
 npm install --save raf
Then as your first import in entry point, before React:
import 'raf/polyfill';

but it appears that just installing --save raf was enough to get the tests running.

**Comment by maxwellbenton** [comment]
Hi @DGMarkel,

Thank you for providing this feedback. We've recently changed the `package.json` file and removed some dependencies that were causing issues. We've confirmed that the current set up is working as expected and will work out of the box.

We apologize for any frustration this may have caused, but thank you for contributing to this lesson!
