### ISSUE TITLE
Error: Method “simulate” is only meant to be run on a single node. 0 found instead.

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/react-forms-lab#28]
When a student received this error on the lab, the reason is because the `ID` in the component does not match the `ID` passed into the find function in the test.

**Comment by maxwellbenton** [comment]
Hi @aisayo,

Thank you for reporting this. We've updated this lesson to address this issue - the id attributes are assigned in the starter code and an additional message has been added noting that these are needed for the tests, which should prevent this issue from happening in the future. 

We apologize for any frustration this may have caused, but thank you for contributing to this lesson!
