### ISSUE TITLE
Extra words in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-forms-lab#29]
You can remove "is currently just" from this sentence, and put "a" before console.log:
"By default, this function is currently just includes console.log that will allow you to see if the form is functioning correctly when working in your browser."

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for spotting this. We have updated this lab and fixed the errors in this sentenance
