### ISSUE TITLE
Prop for LoginForm component incorrect

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/react-forms-lab#35]
In the readme it states:

> This component takes one prop: onSubmit which is a function — this function is called when the form is being submitted. By default, this function currently just includes console.log. That will allow you to see if the form is functioning correctly when working in your browser.

After chatting with a tech coach we decided it should say: This component takes one prop: handleLogin

This is what is actually being passed to the component in App.js:

 <LoginForm handleLogin={this.login} />

**Comment by SallyZ12** [comment]
I agree.  I noticed the same problem when working on the lab today.

**Comment by WSINTRA** [comment]
Also was about to submit a flag but noticed someone already had, thanks

**Comment by john-franti** [comment]
Thanks for submitting this, ran across it today.

**Comment by john-franti** [comment]
Updated. Thanks all.
