### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/react-forms-lab#36]
There was a pretty nasty bug that had to do with webpack version. You'll know it when you run into it.

Solution: 
1. Delete webpack and webpack-dev-server from package.json. Save.
2. Delete package-lock.json
3. Delete the hidden folder, "node_modules". In your terminal run `rm -rf node_modules`
4. `npm install`

This corrected the webpack versioning issue for me.

**Comment by SilverBright** [comment]
This worked.  Thank you!

**Comment by ivillicana** [comment]
If after deleting webpack and webpack-dev-server, you have issues with `npm start`, you may need to upgrade Node to the latest version by running `nvm install --lts`, deleting package-lock.json along with node_modules folder and trying `npm install` again.

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thank you for reporting this issue and providing your solution. We've updated this lesson's `package.json`, confirmed that this lab will work as intended without these packages and have removed them to prevent this issue in the future.

We apologize for any frustration this may have caused, but thank you for contributing to this lesson!
