### ISSUE TITLE
readme refs handleSubmit() -- tests and lab use handleLogin

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/react-forms-lab#39]
according to issue 35, lab was updated? but mine is not. It still reference handleSubmit instead of handle login.

**Comment by maxwellbenton** [comment]
Hi @joanrig,

Thank you for spotting this and providing feedback. We found the remaining reference to `handleSubmit` and have removed it from the Readme, which should resolve this issue.

We apologize for any confusion this may have caused. Thank you for contributing!
