### ISSUE TITLE
"handleSubmit" function does not exist

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/react-forms-lab#40]
"handleSubmit" prop function is actually called handleLogin

**Comment by blainelawson** [comment]
Seconded.

**Comment by maxwellbenton** [comment]
Hi @rossmawd,

Thank you for providing this feedback. We've updated this lesson and removed references to `handleSubmit` to prevent confusion in the future. We apologize for any confusion this may have caused, but thank you for bring this to our attention!
