### ISSUE TITLE
Tests pass in 'dumb' events which cause problems

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/react-forms-lab#6]
The tests pass in events which only have a single property, `target`, which itself only has a single value, `value`:

```js
    it('should call the `onSubmit` callback prop when the form is being submitted', function () {
      // ...
      wrapper.find('#test-username').simulate('change', { target: { value: 'johndoe' } });
      wrapper.find('#test-password').simulate('change', { target: { value: 'supersecret' } });
      // ...
      expect(spy.calledOnce).toBeTruthy('The `onSubmit` prop is not being called exactly once');
    });
```

So, if you try to use the `event` for _anything but_ the `event.target.value`, your tests will fail in a very non-obvious way. For example, one obvious (but failing) way of solving this problem is by adding a `name` to your input like this:

```jsx
          <label>
            Username
            <input
              id="test-username"
              name="username"
              type="text"
              value={this.state.username}
              onChange={this.handleChange} />
          </label>
```

...with a state whose shape looks like this:

```js
    this.state = {
      username: '',
      password: ''
    };
```

...then you might write a change handler like this:

```js
  handleChange(event) {
    const target = event.target;
    this.setState({
      [target.name]: target.value
    });
  }
```

That's gonna fail, because `event.target.name` is undefined.

Similarly, if you do this _other_ obvious solution, where you use the `id` instead of name, it still fails:

```js
    this.state = {
      'test-username': '',
      'test-password': ''
    };
```

...and:

```js
  handleChange(event) {
    const target = event.target;
    this.setState({
      [target.id]: target.value
    });
  }
```

That will fail as well. Instead, in order to pass the tests, you have to do the dirtier way of passing an extra argument bound to the change handler:

```js
  handleChange(field, event) {
    const target = event.target;
    this.setState({
      [field]: target.value
    });
  }
```

...and:

```jsx
          <label>
            Username
            <input
              id="test-username"
              type="text"
              value={this.state.username}
              onChange={this.handleChange.bind(this, 'username')} />
          </label>
```

That's totally unnecessary. All the data you need _should_ be on the `event` object already. And `this.handleChange` already is bound to `this` in the constructor, which means it's not even saving _that_ step.

**Comment by Lukeghenco** [comment]
Thanks @kjleitz, I am going to get this test fixed to work with:

```js
handleChange = event => {
  const target = event.target;
  this.setState({
    [target.name]: target.value
  });
}

**Comment by kjleitz** [comment]
Awesome, glad I could help! :D
